spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-shopp?LocalTimeZone=UTC
    username: postgres
    password: pta1919az
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: create-drop 
  application:
    name: stock-item-service    
server:
  port: 0
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka