spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-shopp
    username: postgres
    password: pta1919az
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: create-drop 
  application:
    name: security-service
server: 
  port: 8081
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka        
    