eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaulZone: http://localhost:8761/eureka
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms-shop-db

  application:
    name: item-service
server:
  port: 0
            